# Problem Set 2
## Standard Library Problems
### Problem 1

In [11]:
def summary(L):
    print(min(L), max(L), sum(L)/len(L))

In [12]:
summary([1, 2, 3, 4])

1 4 2.5


### Problem 2

Integer:

In [13]:
answer = 42

In [14]:
dontpanic = answer

In [15]:
dontpanic = dontpanic + 3

In [16]:
print(dontpanic)

45


In [17]:
print(answer)

42


Thus, since *answer* no longer equals *dontpanic*, integers are immutable.

String:


In [18]:
name = "Jonathan"

In [19]:
person = name

In [20]:
person = "not Jonathan"

In [21]:
print(name)

Jonathan


In [22]:
print(person)

not Jonathan


So strings are also immutable since the two objects are different.

List:

In [23]:
mylist = [1, 2, 3, 'a', 'b', 'c']

In [24]:
thislist = mylist

In [25]:
thislist[1] = 6

In [26]:
print(thislist)

[1, 6, 3, 'a', 'b', 'c']


In [27]:
print(mylist)

[1, 6, 3, 'a', 'b', 'c']


Since both objects are the same, lists are mutable.

Tuple:

In [28]:
mytuple = (4, 5, 6, 'd', 'e', 'f')

In [29]:
thistuple = mytuple

In [30]:
thistuple += (1,)

In [31]:
print(thistuple)

(4, 5, 6, 'd', 'e', 'f', 1)


In [32]:
mytuple

(4, 5, 6, 'd', 'e', 'f')

Since the objects are now different, tuples are immutable.

Set:

In [33]:
myset = {1, 3, 5, 7}

In [34]:
newset = myset

In [35]:
newset.discard(3)

In [36]:
print(newset)

{1, 5, 7}


In [37]:
print(myset)

{1, 5, 7}


Thus, sets are mutable, because both objects are equal.

### Problem 3

In [1]:
import calculator as calc

In [2]:
run calculator

In [5]:
def hyp(a, b):
    return sqrt(calc.add(calc.mult(a, a), calc.mult(b, b)))

In [6]:
hyp(3,4)

5.0

## Introduction to NumPy

### Problem 1


In [5]:
import numpy as np

In [6]:
def ardot():
    A = np.array( [ [3, -1, 4],[1, 5, -9] ] )
    B = np.array([ [ 2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3] ] )
    
    return A @ B

In [7]:
ardot()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

### Problem 2

In [10]:
def myfunction():
    A = np.array( [ [3, 1, 4],[1, 5, 9],[-5, 3, 1] ] )
    
    return -(A @ A @ A) + (9 * (A @ A)) - (15 * A)

In [11]:
myfunction()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Problem 5

In [1]:
import numpy as np
def matfunc():
    A = np.array( [ [0, 2, 4], [1, 3, 5] ] )
    B = np.array( [ [3, 0, 0], [3, 3, 0], [3, 3, 3] ] )
    C = np.array( [ [-2, 0, 0], [0, -2, 0], [0, 0, -2] ] )
    
    row1 = np.column_stack((np.zeros((3,3)), A.T, np.eye(3)))
    row2 = np.column_stack((A, np.zeros((2,2)), np.zeros_like(A)))
    row3 = np.column_stack((B, np.zeros_like(A.T), C))
    newmat = np.concatenate((row1, row2, row3))
    
    return newmat

In [2]:
matfunc()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

## Object Oriented Programming

### Problem 1

In [1]:
class Backpack:
    '''
    A Backpack object class. Has a name, color, and list of objects.

    Attributes:
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        contents (list): the contents of the backpack
    '''
    def __init__(self, name, color, max_size = 5):
        '''
        Set the name, initialize an empty list of contents, set the color and
        set a default maximum number of items.
        
        Parameters:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (int): the maximum number of items the backpack can contain.
        '''

        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []
        
    def put(self, item):
        '''
        Adds an item to the backpack.
        
        Args:
            item (str): name of item to be added to the backpack
        
        Returns:
            "No Room!" if max_size is already reached.
        '''
        if len(self.contents) < 5:
            self.contents.append(item)
            
        else:
            print("No room!")
    
    def take(self, item):
        '''
        Takes an item out of the backpack.
        
        Args:
            item (str): name of the item to be taken out of the backpack
            
        Returns:
            Nothing
        '''
        self.contents.remove(item)
    
    def dump(self):
        '''
        Empties all of the contents of the backpack.
        
        Args:
            None.
        
        Returns:
            Nothing.
        '''
        self.contents = []
        

In [2]:
def test_backpack():
    testpack = Backpack("Barry","black")
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)
    print("Contents:", testpack.contents)

In [3]:
test_backpack()

Contents: ['pencil', 'pen', 'paper', 'computer']


### Problem 2

In [15]:
class Jetpack(Backpack):
    '''
    A Jetpack object class. Inherits from the Backpack class.

    Attributes: 
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): the maximum number of items the backpack can contain.
        contents (list): the contents of the backpack.
        fuel (int): the amount of fuel in the tank.
    '''
    def __init__(self, name, color, max_size = 2):
        '''
        Set the name, initialize an empty list of contents, set a color, set a default
        maximum number of items, and set a default amount of fuel.
        
        Args:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (int): the maximum number of items the backpack can contain (default = 2).
            fuel (int): the amount of fuel in the tank (default =10).
        '''
        
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
    
    def fly(self, burnamnt):
        '''
        Flies and burns fuel if there is enough fuel to burn the specified amount.
        
        Args:
            burnamnt (int): amount of fuel to be burned
            
        Returns:
            "Not enough fuel!" if the amount entered is greater than the amount in the tank (i.e. 
            the number in "fuel.")
        '''
        if burnamnt > fuel:
            print("Not enough fuel!")
            
        else:
            fuel = fuel - burnamnt
        
    def dump(self):
        '''
        Empties all the contents of the backpack and all of the fuel.
        
        Args:
            None.
        
        Returns:
            Nothing.
        '''
        self.contents = []
        self.fuel = 0
    